### ISSUE TITLE
Installation make error

### ISSUE THREAD

**Issue by dandil** [daormar/thot#5]
Hi, I'm having an issue running the make command on installation. Seems to be an ar command with no file inputs somewhere. Running on macOS Sierra. Output is below:
`$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
Making all in nlp_common
make[3]: Nothing to be done for `all'.
Making all in incr_models
make[3]: Nothing to be done for `all'.
Making all in sw_models
make[3]: Nothing to be done for `all'.
Making all in phrase_models
make[3]: Nothing to be done for `all'.
Making all in smt_preproc
make[3]: Nothing to be done for `all'.
Making all in error_correction
make[3]: Nothing to be done for `all'.
Making all in downhill_simplex
make[3]: Nothing to be done for `all'.
Making all in stack_dec
make[3]: Nothing to be done for `all'.
Making all in exper
make[3]: Nothing to be done for `all'.
Making all in testing
make[3]: Nothing to be done for `all'.
Making all in hat_trie
make[3]: Nothing to be done for `all'.
/bin/sh ../libtool  --tag=CC   --mode=link gcc -W -Wno-deprecated -I./nlp_common -I./incr_models -I./sw_models -I./phrase_models -I./smt_preproc -I./error_correction -I./downhill_simplex -I./stack_dec -I./hat_trie -DTHOT_MASTER_INI_PATH=\"/usr/local/share/thot/ini_files/master.ini\" -DTHOT_LIBDIR=\"/usr/local/lib\" -Ino/src/include  -g -O2 -g -Wall -O2   -o libhattrie.la -rpath /usr/local/lib    -lm 
libtool: link: gcc -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libhattrie.0.dylib   -lm  -g -O2 -g -O2   -install_name  /usr/local/lib/libhattrie.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
libtool: link: (cd ".libs" && rm -f "libhattrie.dylib" && ln -s "libhattrie.0.dylib" "libhattrie.dylib")
libtool: link: ar cru .libs/libhattrie.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[3]: *** [libhattrie.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
`

**Comment by daormar** [comment]
Hi, there were some portability issues causing the error you report. Could you please execute `git pull` and see if now works?

**Comment by dandil** [comment]
Works like a charm. Thanks
