### ISSUE TITLE
Windows support.

### ISSUE THREAD

**Issue by giorgiozoppi** [daormar/thot#6]
I open this ticket for porting stuff to windows native since it might be useful tool in Win32 panorama. Please assign this to me.
The port:
1. Use cmake and build.
2. Get rid of Posix code to a indipendent cpp11/cpp14 code/boost

**Comment by daormar** [comment]
Sorry for the delayed response. Could you please provide more details about the work to be done and how could it be structured?

Currently it is possible to use Thot in Windows systems by means of Cygwin. In the past we were also able to compile a part of the C++ code using MinGW, however such capability was discontinued.

On the other hand, the project actively pursues the use of Posix code to increase portability, I was wondering what would be the goal behind the transition to cpp11/cpp14 you mention in your post?

**Comment by giorgiozoppi** [comment]
What it might be desirable is using directly without cygwin tranlations layer. The idea is to use all new C++ features and libuv or boost features for  making natively ok platform independent. The first step is having a cmake build
