### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by lchunleo** [daormar/thot#8]
hi 

i am trying to use the thot_tokenize and noted the following issues:

1) error in the tok_sent.encode function
2) no thot_smt_preproc module

and also when i try out the => thot_tm_train -s ${src_train_corpus} -t ${trg_train_corpus} -o tm
there is only folder created but there is no desciptor files in it.

**Comment by daormar** [comment]
Hi, could you please tell in which operating system are you trying to use the tool?

**Comment by daormar** [comment]
I close this issue due to lack of response.
