### ISSUE TITLE
Installation on Ubuntu18, Python2 vs Python3 print statements

### ISSUE THREAD

**Issue by AlexSkrn** [daormar/thot#9]
After installation of the Thot package on a newly installed Ubuntu18, 'make installcheck' threw an error when performing 'Tuning log-linear model weights', file 'thot_get_nblist_segm_info', line 99, print line.encode('utf-8'), syntax error. I modified print statements in all of the files containing Python code in the source files directory to comply with Python3. After that I ran installation again and then 'make installcheck' showed that all tests passed.

**Comment by daormar** [comment]
Thanks for bringing this issue. When experiencing problems with Python versions, have you tried to use this option when executing configure?

make clean
./configure PYTHON=/usr/bin/python2.7 ... # adapt the Python2 path depending on your installation
make
make install

Could you please check if the previous instructions solve the problem without the necessity of modifying the code?

**Comment by AlexSkrn** [comment]
Hi, could you please clarify what 'make clean' is going to do exactly? Will running 'make clean' reverse the changes in the source code I made? Because if it doesn't, then the modified source code will not work with Python2.7 (because <print('something', end='')> will be illegal). On the other hand, if it does reverse the changes, then I would like to back up my changes before running 'make clean.'

**Comment by daormar** [comment]
Thanks for checking it! I close the issue.
